# OpenAPI Contract: AI Chat Endpoint

```yaml
openapi: 3.0.0
info:
  title: AI Chat API for Todo Application
  description: API for conversational todo management
  version: 1.0.0

paths:
  /api/v1/ai/chat:
    post:
      summary: Process natural language input for todo management
      description: Accepts natural language input and processes it through the AI agent to perform todo operations
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
                  description: Natural language command from user
                  example: "Add a task to buy groceries tomorrow"
                sessionId:
                  type: string
                  description: Optional session ID for maintaining context
                  example: "sess_abc123"
      responses:
        '200':
          description: AI response with action plan
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      responseText:
                        type: string
                        description: Natural language response to user
                        example: "I've created a task 'buy groceries' for tomorrow."
                      requiresConfirmation:
                        type: boolean
                        description: Whether user confirmation is needed for actions
                      actionPlan:
                        type: array
                        items:
                          type: object
                          properties:
                            operation:
                              type: string
                              enum: [CREATE, UPDATE, DELETE, SEARCH, MARK_COMPLETE, MARK_INCOMPLETE]
                            endpoint:
                              type: string
                              description: Backend API endpoint to call
                              example: "/api/v1/tasks"
                            method:
                              type: string
                              enum: [GET, POST, PUT, PATCH, DELETE]
                            payload:
                              type: object
                              description: Data to send with the API call
                      detectedIntent:
                        type: object
                        properties:
                          type:
                            type: string
                            enum: [CREATE_TASK, UPDATE_TASK, DELETE_TASK, SEARCH_TASKS, MARK_COMPLETE, MARK_INCOMPLETE, SET_PRIORITY, SET_DUE_DATE, SET_REMINDER, CREATE_RECURRING_TASK]
                          parameters:
                            type: object
                            description: Extracted parameters from user input
                  error:
                    type: object
                    nullable: true
        '400':
          description: Bad request - invalid input or failed validation
        '401':
          description: Unauthorized - invalid or missing authentication
        '500':
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
```